### ISSUE TITLE
Allow to don't save on __exit__

### ISSUE THREAD

**Issue by philae-ael** [OpenPathView/DirectoryManagerClient#7]
What I would expect:
```python
with self._opv_directory_manager.Open(uuid, mode="ro") as (path_uuid, panorama_path):
     # do things, modify files...
# Here, __exit__ have been called but file have no changed server side
```

**Comment by Benvii** [comment]
Exit/save will push only modified files (based on last change date).
If nothing was changed it will not push anything.

**Comment by philae-ael** [comment]
What I mean is an option that allow you to change files (add, modify...) only on local side. For instance when you copy the pto file from a dir to another
